#!/bin/sh

# Runs strip-debug-cli on all JavaScript files in lib/
# This removes all instances of:
#
#   debugger;
#   console.log();
#   console.assert();
#   ...etc.
#
# Intended to be run in npm prepack hook.

set -e

find lib -name '*.js' | while read -r filename; do
    # Create a back-up, in case things go south.
    cp "${filename}" "${filename}.bak"
    npx strip-debug "${filename}.bak" > "${filename}"
    # It's safe to remove the backup now.
    rm "${filename}.bak"
done
